### ISSUE TITLE
std::bad_alloc crash for certain windows users.

### ISSUE THREAD

**Issue by sdhawk** [TheZoc/ZPatcher#13]
This might be way too vague for the issues system, but this seems like the only point of contact so I went for it.

- When updating via ZLauncher to a specific patch users get a popup reading "*** Caught unhandled unknown exception; terminating" and the launcher just stays on "Applying Patch, Please Wait..." (still functional enough to complain about closing it while applying a patch)
- Not everyone gets the error: works fine on 5 different computers, but another 4 computers have the crash. Only obvious common point is that most of the users who crash are on Windows 7, while those who it works for tend to be 8 or 10. One win10 computer still has the crash, though. Works fine for me personally, and I don't have direct access to the computers having issues.
- Was compiled on 8.1 using Visual Studio 2015 with x64.
- Using wxWidget's OnUnhandledException() override I was able to find that it's getting a std::bad_alloc exception, but I can't get a full stack trace out of it using wxWidget's debugrpt tools: OnFatalException() doesn't get called from it, and doing the reporting in OnUnhandledException() or OnExceptionInMainLoop() just gets the stack for current error handling rather than what threw it.
- Trying again (after restoring the backups) or performing the patch process from scratch results in the same error consistently for users.
- The ZLauncher log file ends on "Writing File: ./py/map/state/new_round.py" (part of a replace operation). There was only one more file it needed to perform a replace operation on (py/network/sanitize.py). It seems to write the new version of the new_round.py file correctly before crashing.
- Nothing exceptional about the patch: it's quite small, only changes less than 20 files, and doesn't involve updating the patcher itself. There are only about 12 total patches in the configuration currently.
- This is all using the current version of ZPatcher (as of this posting) with minimal modifications. Patches were created with the command line tool.

The relevant patch files can be provided if necessary, but I'd prefer to do so privately.

**Comment by TheZoc** [comment]
Hello @sdhawk !

I'll be happy to assist you privately!

I can be reached on [Twitter (@zoc)](https://twitter.com/zoc) through direct messages. If you don't use twitter, let me know and we will get another way to get in touch.

Cheers!

**Comment by sdhawk** [comment]
Thanks! 

Out of curiosity I had one of the error users try it with a 32-bit version and we finally got log output from it:

> Writing File: ./py/map/state/new_round.py
> Undefined operation (37) requested for file ª‡MKíñŸÂo (garbage characters continue)

So it seems like somewhere in the decompression process (or perhaps elsewhere) the position in the file is getting thrown off due to some system-specific factor (probably sizes?). I'll continue poking at it and let you know if I isolate the problem.

**Comment by sdhawk** [comment]
After a whole lot of frustration it became apparent that the only possible thing that could be throwing off the file position would be the fseek/ftell functions themselves. It turns out that this is a very specific issue with the Windows 8.1 SDK that has been fixed in more recent updates of Windows 10, hence the inconsistency in who it affected. You can read the full details here: https://social.msdn.microsoft.com/Forums/Lync/en-US/8c4d27db-1128-4803-951b-fef515455a03/vs2015-non-accurate-fseekfread-operation?forum=vcgeneral

Changing the target platform version to 10.0.16299.0 wasn't enough, I had to also include the Win10 sdk UCRT dlls to fix it for affected users (presumably a fixed vs redistributable for 2017 might eventually fix this in the future?). 

So not really a problem with ZPatcher itself, in the end. You can close this.
