### ISSUE TITLE
abandoned?

### ISSUE THREAD

**Issue by voltuer** [TheZoc/ZPatcher#19]

**Comment by TheZoc** [comment]
Hello @sebolio,

No, the project is in a stable state. I use it on a few personal projects. I've also been contacted many times about forks and for it being used in private projects. I asked for them to contribute back, but I assume they preferred to keep the code to themselves.

Feel free to use it! If you encounter an issue, please, let me know and I'll help as best as I can.

If you improve the code, I'd appreciate if you could do a PR to merge the improvements.

Thank you very much!
