### ISSUE TITLE
Directory problem

### ISSUE THREAD

**Issue by edcolmar** [TheZoc/ZPatcher#23]
Branch: Version3
Environment:  Windows10  VS2019 latest

This is likely a configuration issue with VS, but I have not been able to figure this out, and I expect others will experience a similar problem, so I hope you can help to resolve this one.

Installing all prerequisites manually worked fine.  
Retarget projects to latest worked fine.

Building results in a malformed directory on all projects, and the following error:

Error	MSB3191	Unable to create directory "C:\ue_projects\ZPatcher\ZPatcherLib\C:\ue_projects\ZPatcher\_Intermediate\x64\Debug\ZPatcherLib". The given path's format is not supported.	ZPatcherLib	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets	998	

Note the duplicate C:\ue_projects\ZPatcher\ in the path.  

Do you happen to have any suggestions on how to fix the directory location?

**Comment by TheZoc** [comment]
Oh, I haven't tested in VS2019.
I'll download it and give it a try :)

Did you change any configs?
What tools version are you using, when trying to compile? (You can see that in the project properties)

**Comment by TheZoc** [comment]
@edcolmar What version are you trying to compile?
Is that the `master` branch, or the `version3` branch?

Trying to compile the `version3` branch here with VS2019 worked our without any modifications on the project.

**Comment by edcolmar** [comment]
Branch: Version3
Environment: Windows10 VS2019 latest

I did not change any configs.

Tools version is an unknown.  Where do I find this?

**Comment by TheZoc** [comment]
@edcolmar The tools should appear when trying to open the solution with Visual Studio 2019.

Do you mind to try to start from scratch again, just in case? :)

Clone the git repository with full submodules on the right branch:
```bash
git clone --recurse-submodules -b version3 https://github.com/TheZoc/ZPatcher.git
```

Setup the dependencies. You can check the details in the [Compiling.md](https://github.com/TheZoc/ZPatcher/blob/version3/docs/Compiling.md) file for version 3, or follow the [setup script I use for continuous integration](https://github.com/TheZoc/ZPatcher/blob/version3/setup-external-dependencies.ps1).

Open the solution file in Visual Studio 2019 and let me know how it goes, please :)

**Comment by edcolmar** [comment]
Confirmed.  I installed a fresh VS2019 on a different machine, and compiling worked successfully.  

My other machine with the directory issue is used for UE development.  

I am lacking VS troubleshooting and configuration skills, so I'm at a loss to explain how or why this is happening on a dirty VS install...  

Anyway, thanks for the follow up and suggestions.
