### ISSUE TITLE
Up to date message on startup

### ISSUE THREAD

**Issue by edcolmar** [TheZoc/ZPatcher#24]
Zpatcher has been working great for me for my project for the past few months.  However, on my most recent patch something broke.  New users downloading for the first time get the "up to date" message on startup, with no downloading or patching at all.  But, users who were at the previous version were able to patch successfully.  What could be causing this?

**Comment by TheZoc** [comment]
Hi @edcolmar,
I'll need more info to determine the issue.
The first place I'd look is the XML with the patch information.
Are you able to provide it?

**Comment by edcolmar** [comment]
Sure.  It is here:

https://uetopia.com/gamepatch/5764417417379840/manifest.xml

**Comment by edcolmar** [comment]
After looking through it more carefully, you were right.  I messed up the numbering on the patches.  After correcting the numbering, it is working again correctly.  Thanks for the hint!
